-- Criar nova tabela works
CREATE TABLE IF NOT EXISTS works (
    id UUID PRIMARY KEY NOT NULL,
    origin VARCHAR(255),
    appearance VARCHAR(255),
    scent VARCHAR(255),
    color VARCHAR(50),
    weight BIGINT NULL,
    post_processing_weight BIGINT NULL,
    post_processing_revenue BIGINT NULL,
    post_processing_delivered BIGINT NULL,
    post_processing_residue BIGINT NULL,
    residue_rate BIGINT NULL,
    start_at DATE,
    observation TEXT,
    product_type VARCHAR(50),
    status VARCHAR(50),
    beekeeper_id UUID,
    owner_id UUID,
    org_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (beekeeper_id) REFERENCES beekeepers(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (org_id) REFERENCES users(id)
);